// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAWnA2FreSa7uitTr9Z00kkGWexyoR6A',
    appId: '1:741924593201:web:339e63682fea92784abf10',
    messagingSenderId: '741924593201',
    projectId: 'store-app-35cf4',
    authDomain: 'store-app-35cf4.firebaseapp.com',
    storageBucket: 'store-app-35cf4.firebasestorage.app',
    measurementId: 'G-LNPM0QJE3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9hI2iwtr9nlkMkROVz7pvY1m4JSY5bc',
    appId: '1:741924593201:android:b22bab66cf3c907d4abf10',
    messagingSenderId: '741924593201',
    projectId: 'store-app-35cf4',
    storageBucket: 'store-app-35cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl9jP7rd4s4coKQsPMiN8peNZSDBZvjhw',
    appId: '1:741924593201:ios:670993ae233713714abf10',
    messagingSenderId: '741924593201',
    projectId: 'store-app-35cf4',
    storageBucket: 'store-app-35cf4.firebasestorage.app',
    iosBundleId: 'com.example.flutterStoreAppWithGraphql',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl9jP7rd4s4coKQsPMiN8peNZSDBZvjhw',
    appId: '1:741924593201:ios:670993ae233713714abf10',
    messagingSenderId: '741924593201',
    projectId: 'store-app-35cf4',
    storageBucket: 'store-app-35cf4.firebasestorage.app',
    iosBundleId: 'com.example.flutterStoreAppWithGraphql',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsAWnA2FreSa7uitTr9Z00kkGWexyoR6A',
    appId: '1:741924593201:web:2d216284aedd4f1b4abf10',
    messagingSenderId: '741924593201',
    projectId: 'store-app-35cf4',
    authDomain: 'store-app-35cf4.firebaseapp.com',
    storageBucket: 'store-app-35cf4.firebasestorage.app',
    measurementId: 'G-8RMZWK2ZNM',
  );
}
